server:
  port: 8090
spring:
  data:
    redis:
      password: 1234
  datasource:
    password: 1234
custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
